### ISSUE TITLE
JS merging breaks

### ISSUE THREAD

**Issue by nahall** [elgentos/ExtendedAoeJsCssTstamp#1]
Hello, your extension seems to work without JS merging enabled, but when I enable JS merging in Magento it causes an exception that breaks everything, including the backend. This extension needed to be disabled in order to disable JS merging in the backend. The stack trace is below:

`
2017-02-24T20:47:01+00:00 ERR (3): 
exception 'Exception' with message 'No content found in files:
/var/websites/site/www/js/prototype/prototype.1487969221.js
/var/websites/site/www/js/prototype/window.1487969221.js
/var/websites/site/www/js/scriptaculous/builder.1487969221.js
/var/websites/site/www/js/scriptaculous/effects.1487969221.js
/var/websites/site/www/js/scriptaculous/dragdrop.1487969221.js
/var/websites/site/www/js/scriptaculous/controls.1487969221.js
/var/websites/site/www/js/scriptaculous/slider.1487969221.js
/var/websites/site/www/js/lib/ccard.1487969221.js
/var/websites/site/www/js/prototype/validation.1487969221.js
/var/websites/site/www/js/varien/js.1487969221.js
/var/websites/site/www/js/mage/translate.1487969221.js
/var/websites/site/www/js/mage/adminhtml/hash.1487969221.js
/var/websites/site/www/js/mage/adminhtml/events.1487969221.js
/var/websites/site/www/js/mage/adminhtml/loader.1487969221.js
/var/websites/site/www/js/mage/adminhtml/grid.1487969221.js
/var/websites/site/www/js/mage/adminhtml/tabs.1487969221.js
/var/websites/site/www/js/mage/adminhtml/form.1487969221.js
/var/websites/site/www/js/mage/adminhtml/accordion.1487969221.js
/var/websites/site/www/js/mage/adminhtml/tools.1487969221.js
/var/websites/site/www/js/mage/adminhtml/uploader.1487969221.js
/var/websites/site/www/js/mage/adminhtml/product.1487969221.js
/var/websites/site/www/js/calendar/calendar.1487969221.js
/var/websites/site/www/js/calendar/calendar-setup.1487969221.js' in /var/websites/site/www/app/code/core/Mage/Core/Helper/Data.php:750
Stack trace:
#0 /var/websites/site/www/app/code/community/Aoe/JsCssTstamp/Model/Package.php(235): Mage_Core_Helper_Data->mergeFiles(Array, '/var/websites/s...', false, Array, 'js')
#1 /var/websites/site/www/app/code/community/Aoe/JsCssTstamp/Model/Package.php(82): Aoe_JsCssTstamp_Model_Package->generateMergedUrl('js', Array, '/var/websites/s...', 'eb9dda869753cb7...')
#2 [internal function]: Aoe_JsCssTstamp_Model_Package->getMergedJsUrl(Array)
#3 /var/websites/site/www/app/code/local/Elgentos/ExtendedAoeJsCssTstamp/Block/Adminhtml/Page/Html/Head.php(59): call_user_func(Array, Array)
#4 /var/websites/site/www/app/code/core/Mage/Page/Block/Html/Head.php(214): Elgentos_ExtendedAoeJsCssTstamp_Block_Adminhtml_Page_Html_Head->_prepareStaticAndSkinElements('<script type="t...', Array, Array, Array)
#5 /var/websites/site/www/app/design/adminhtml/default/default/template/page/head.phtml(40): Mage_Page_Block_Html_Head->getCssJsHtml()
#6 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(241): include('/var/websites/s...')
#7 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#8 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#9 /var/websites/site/www/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#10 /var/websites/site/www/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#11 /var/websites/site/www/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#12 /var/websites/site/www/app/design/adminhtml/default/default/template/page.phtml(43): Mage_Core_Block_Abstract->getChildHtml('head')
#13 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(241): include('/var/websites/s...')
#14 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#15 /var/websites/site/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 /var/websites/site/www/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#17 /var/websites/site/www/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#18 /var/websites/site/www/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#19 /var/websites/site/www/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#20 /var/websites/site/www/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(119): Mage_Core_Controller_Varien_Action->renderLayout()
#21 /var/websites/site/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#22 /var/websites/site/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#23 /var/websites/site/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 /var/websites/site/www/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#25 /var/websites/site/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#26 /var/websites/site/www/index.php(83): Mage::run('', 'store')
#27 {main}
`

**Comment by peterjaap** [comment]
Sorry, we don't use merging (merging is considered bad practice when using HTTP/2) so I won't invest time to tackle this. If you have fixed the problem, you're more than welcome to submit a PR.

**Comment by nahall** [comment]
We don't use merging either (it was enabled by accident which is how I found the bug) but I thought you might want to know since if anyone else tries enabling merging with your extension it breaks Magento until disabled, and it is cumbersome to disable once this happens.
