### ISSUE TITLE
Not Needed Any More?

### ISSUE THREAD

**Issue by sprankhub** [elgentos/ExtendedAoeJsCssTstamp#2]
Thanks a lot for this addition. I spoke with AOE and together, we updated https://github.com/AOEpeople/Aoe_JsCssTstamp. It now also adds timestamps to the JS files under `/js` and also handles admin files. Hence, I think this extension is not necessary any more. Could you please check it and maybe deprecate this extension @peterjaap?

**Comment by sanderjongsma** [comment]
@sprankhub thanks for mentioning. Seems like https://packagist.org/packages/aoepeople/aoe_jscsststamp did not update automatically. Can you fix this so I can update the package with composer.

**Comment by sprankhub** [comment]
Unfortunately, I cannot. But I created an [issue for it](https://github.com/AOEpeople/Aoe_JsCssTstamp/issues/14).

**Comment by sanderjongsma** [comment]
Thank you. I will deprecate this module by the time.

**Comment by peterjaap** [comment]
Module is deprecated.
